# coding: utf-8
"""
tech_news_crawler.py
====================

This script provides a simple framework for automatically gathering
technology‑related news articles and research updates from a set of RSS
feeds.  It leverages the widely used ``feedparser`` library to fetch
and parse RSS or Atom feeds and uses ``BeautifulSoup`` from
``bs4`` to strip HTML from article summaries.  The script can be
extended to support additional feeds, including unofficial feeds for
WeChat public accounts generated by community projects such as
``WeChat‑Feeds`` (see the accompanying documentation for links).

**Key features**

* A configurable list of RSS/Atom feed URLs covering major technology
  news outlets (The Verge, Ars Technica, TechCrunch, Hacker News, etc.),
  popular AI/tech newsletters (ByteByteGo, Ben's Bites), curated
  discovery sites (Product Hunt), venture capital blogs, personal
  technical blogs, and research journals (MIT Technology Review and
  Nature).  The list can be edited to include additional sources or
  WeChat RSS feeds generated via third‑party services.

* A ``fetch_feed`` function that retrieves and parses each feed using
  ``feedparser``, extracting commonly available fields such as
  ``title``, ``link``, ``summary`` and ``published``.  When a
  ``content:encoded`` tag is present (common in WordPress feeds) it is
  preferred over the shorter summary.

* Automatic removal of HTML tags from the summary using
  ``BeautifulSoup`` to produce clean, plain‑text descriptions.

* A ``filter_articles`` function that optionally filters the list of
  articles by keywords (for example, ``['breakthrough', '突破', '重大']``)
  to focus on major breakthroughs or specific topics.

* A ``save_as_markdown`` helper that writes the collected articles
  to a markdown file.  Each entry includes the publication date,
  source, title and summary with a hyperlink back to the original
  article.

Usage
-----

1. Install the dependencies.  From a terminal on a machine with
   Internet access run::

       pip install feedparser beautifulsoup4

2. Adjust the ``FEED_URLS`` list below.  You can add or remove any
   RSS/Atom feeds.  To include WeChat public accounts you must first
   obtain an RSS feed URL; projects such as `wechat‑feeds` provide
   static RSS files on GitHub for many public accounts.

3. Execute the script.  By default it will print the titles and
   publication dates of recent articles.  You can call
   ``save_as_markdown`` to persist the results.

The functions are written to be modular so you can integrate them into
larger automation workflows (e.g. scheduled jobs, web services or
notebooks).
"""

from __future__ import annotations

import datetime

import logging
from typing import Iterable, List, Dict, Any, Optional

import feedparser
from bs4 import BeautifulSoup

import pandas as pd

# Configure basic logging.  You can adjust the level to DEBUG for
# verbose output when troubleshooting.
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

def strip_html(html: str) -> str:
    """Remove HTML tags from a snippet using BeautifulSoup.

    Parameters
    ----------
    html : str
        The raw HTML fragment extracted from an RSS feed.

    Returns
    -------
    str
        Plain text with tags removed.
    """
    soup = BeautifulSoup(html, "html.parser")
    return soup.get_text(separator=" ", strip=True)

def fetch_feed(url: str) -> List[Dict[str, Any]]:
    """Fetch a single RSS/Atom feed and extract article metadata.

    Parameters
    ----------
    url : str
        The RSS or Atom feed URL.

    Returns
    -------
    List[Dict[str, Any]]
        A list of article dictionaries.  Each dictionary contains
        ``source`` (the feed URL), ``title``, ``link``, ``published``
        (as a ``datetime`` object if available) and ``summary``.
    """
    logging.debug("Fetching feed %s", url)
    parsed = feedparser.parse(url)
    articles: List[Dict[str, Any]] = []
    for entry in parsed.entries:
        title: str = entry.get("title", "").strip()
        link: str = entry.get("link", "").strip()
        # Determine publication date if available
        published_parsed = entry.get("published_parsed") or entry.get("updated_parsed")
        if published_parsed:
            published = datetime.datetime(*published_parsed[:6])
        else:
            published = None
        # Prefer full content over summary when present
        if "content" in entry and entry.content:
            content_html = entry.content[0].value
        elif "summary" in entry:
            content_html = entry.summary
        else:
            content_html = ""
        summary = strip_html(content_html)
        articles.append(
            {
                "source": parsed.feed.get("title", url),
                "feed_url": url,
                "title": title,
                "link": link,
                "published": published,
                "summary": summary,
            }
        )
    logging.info("Fetched %d articles from %s", len(articles), url)
    return articles

def fetch_all_feeds(urls: Iterable[str]) -> List[Dict[str, Any]]:
    """Fetch multiple feeds and combine the articles into a single list.

    Parameters
    ----------
    urls : iterable of str
        A collection of RSS or Atom feed URLs.

    Returns
    -------
    List[Dict[str, Any]]
        All articles from the provided feeds.  The list is unsorted.
    """
    all_articles: List[Dict[str, Any]] = []
    for url in urls:
        try:
            feed_articles = fetch_feed(url)
            all_articles.extend(feed_articles)
        except Exception as exc:
            logging.error("Error fetching feed %s: %s", url, exc)
    return all_articles

def filter_articles(
    articles: Iterable[Dict[str, Any]], keywords: Optional[List[str]] = None
) -> List[Dict[str, Any]]:
    """Filter a list of articles by one or more keywords.

    Parameters
    ----------
    articles : iterable of dict
        The article dictionaries produced by ``fetch_feed`` or
        ``fetch_all_feeds``.
    keywords : list of str or None, optional
        If provided, only articles whose titles or summaries contain at
        least one of the keywords (case‑insensitive) will be returned.
        When ``None``, no filtering is applied.

    Returns
    -------
    list of dict
        The filtered articles.  The ordering is unchanged from the
        original list.
    """
    if not keywords:
        return list(articles)
    keywords_lower = [kw.lower() for kw in keywords]
    filtered: List[Dict[str, Any]] = []
    for article in articles:
        haystack = f"{article.get('title', '')} {article.get('summary', '')}".lower()
        if any(kw in haystack for kw in keywords_lower):
            filtered.append(article)
    logging.info("Filtered down to %d articles using keywords %s", len(filtered), keywords)
    return filtered

def sort_articles_by_date(articles: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Sort articles by their publication date in descending order.

    Articles without a publication date are placed at the end of the list.
    """
    return sorted(
        articles,
        key=lambda a: a.get("published") or datetime.datetime.min,
        reverse=True,
    )

def save_as_markdown(
    articles: Iterable[Dict[str, Any]], filename: str = "tech_news.md"
) -> None:
    """Save a collection of articles to a Markdown file.

    Parameters
    ----------
    articles : iterable of dict
        The articles to save, ideally sorted by date.
    filename : str, optional
        Destination filename for the Markdown output.  Defaults
        to ``tech_news.md``.
    """
    lines: List[str] = []
    for article in articles:
        pub_date = article.get("published")
        date_str = pub_date.strftime("%Y-%m-%d %H:%M") if pub_date else "Unknown date"
        lines.append(f"### {article['title']}")
        lines.append(f"- **Date:** {date_str}")
        lines.append(f"- **Source:** {article['source']}")
        lines.append(f"- **Link:** [{article['link']}]({article['link']})")
        if article.get("summary"):
            lines.append(f"- **Summary:** {article['summary']}")
        lines.append("")  # blank line between entries
    with open(filename, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    logging.info("Saved %d articles to %s", len(list(articles)), filename)

# Default list of technology and science feeds.  Feel free to add or remove
# entries.  For WeChat public accounts you will need to supply a valid RSS
# URL (for example, a feed generated by the ``wechat‑feeds`` project).  See
# the accompanying documentation for details on obtaining such URLs.

"""
FEED_URLS: List[str] = [
    # Major technology news outlets
    "https://www.theverge.com/rss/index.xml",      # The Verge
    "https://feeds.arstechnica.com/arstechnica/index",  # Ars Technica
    "https://techcrunch.com/feed/",                 # TechCrunch
    # Community and curated feeds
    "https://hnrss.org/frontpage?points=100",       # Hacker News front page (100+ points)
    "https://blog.bytebytego.com/feed",            # ByteByteGo newsletter
    "https://bensbites.beehiiv.com/feed",          # Ben's Bites newsletter
    "https://www.producthunt.com/feed",            # Product Hunt launches
    # Bonus and VC/analysis feeds
    "https://rss.beehiiv.com/feeds/2R3C6Bt5wj.xml", # The Rundown AI digest
    "https://stratechery.com/feed/",               # Stratechery (Ben Thompson)
    "https://a16z.com/feed/",                      # Andreessen Horowitz VC blog
    "https://simonwillison.net/atom/everything/",  # Simon Willison's tech blog
    # Research and science journals
    "https://www.technologyreview.com/feed/",       # MIT Technology Review
    "http://feeds.nature.com/nature/rss/current",  # Nature journal current issue
    # Additional feeds can be added below, e.g. WeChat public account feeds
    # generated by the wechat‑feeds project.  Example:
    # "https://raw.githubusercontent.com/hellodword/wechat-feeds/feeds/<encoded_id>.xml",
]

"""


df = pd.read_excel("tech_news_sources.xlsx")
FEED_URLS = df["Feed URL"].dropna().tolist()


if __name__ == "__main__":
    # Example usage: fetch and print recent articles.  You can add keyword
    # filtering here or save to a file.
    articles = fetch_all_feeds(FEED_URLS)
    # Optionally filter by major breakthroughs

    """    keywords = ["breakthrough", "milestone", "first-ever", "record",
                    "重大突破", "首次实现", "刷新纪录", "关键进展",
                    "重大进展", "里程碑", "突破性",    "AI", "artificial intelligence", "大模型", "生成式", "AGI",
                "cybersecurity", "security", "漏洞", "攻击", "零日",
                "quantum", "量子计算", "量子通信",
                "chip", "semiconductor", "芯片", "算力",
                "robot", "brain-computer", "fusion", "氢能", "脑机接口", "policy", "export control", "sanction",
                "标准", "法规", "战略", "国家级"
                    ]"""
    df = pd.read_excel("OverSeer_tech_keywords.xlsx")
    language_cols = [
        "keywords_en",
        "keywords_cn",
        "keywords_jp",
        "keywords_kr",
        "keywords_ru",
        "keywords_es",
    ]

    keywords = []
    for _, row in df.iterrows():
        if row["Enabled"] == 1:
            for col in language_cols:
                val = row.get(col)
                if pd.notna(val) and str(val).strip():
                    keywords.append(str(val).strip())

    keywords = list(dict.fromkeys(keywords))
    filtered = filter_articles(articles, keywords)
    # Sort by date and keep the top 20
    # 按日期排序，全部保留
    sorted_articles = sort_articles_by_date(filtered)

    # 写入 Excel
    rows = []
    for art in sorted_articles:
        rows.append({
            "published": art["published"].strftime("%Y-%m-%d %H:%M") if art["published"] else "",
            "title": art.get("title", ""),
            "source": art.get("source", ""),
            "link": art.get("link", ""),
            "summary": art.get("summary", ""),
            "feed_url": art.get("feed_url", ""),
        })

    df = pd.DataFrame(rows)

    today_str = datetime.datetime.today().strftime("%Y-%m-%d")
    output_filename = f"{today_str}_OverseerTodayResult.xlsx"
    df.to_excel(output_filename, index=False)

    print(f"已保存到 Excel: {output_filename}")
